name: GitHub metrics as SVG image
on:
  schedule: [{cron: "0 22 * * *"}]
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          user: mrBackSlash-it
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_pagespeed: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_isocalendar: yes
